#!/bin/sh

NDIR=$HOME/.netscape
PFILE=$NDIR/preferences.js
CFFILE=$NDIR/fontsz.cf
TMPFILE=$NDIR/fontsz.sed

die() {
	echo "notscape: can't $*" >&2
	exit 1
}

[ -r $CFFILE ] && {
awk '{ printf("/intl.font_spec_list/s/-[^-]*-\\([^-]*\\)-%s,/-%s-\\1-%s,/\n", \
	$1, $2, $1); }' <$CFFILE >$TMPFILE

cp $PFILE $PFILE.old || die "save old pref file"
sed -f $TMPFILE <$PFILE.old >$PFILE.new || die "create new pref file"
[ -s $PFILE.new ] || die "create new pref file"

mv $PFILE.new $PFILE || die "install new pref file"

}

exec netscape -no-about-splash "$@"
