#!/bin/sh
CONFLOCAL=$HOME/.netscape/psfonts.cf
CONFGLOBAL=/usr/local/etc/nspsfonts.cf

if [ -r "$CONFLOCAL" ]
then
	CONF="$CONFLOCAL"
else
	CONF="$CONFGLOBAL"
fi

grep -v "^#" <$CONF | grep -v "^$" | while :
do {
	read nsname base afm pfa x
	[ -z "$nsname" ] && break;

	fname=`awk '/^FontName/ {print $2;}' <$base$afm`

	cat $base$pfa
	echo "/$nsname /$fname findfont definefont"

} done

grep -v "^	/Encoding isolatin1encoding def$" | egrep -v '^newpath .* closepath clip newpath$'
