#!/usr/bin/perl
#
# A script to convert a Unicode character map to
# the C code
#

sub fromhex
{
	return eval "0x".$_[0];
}

$inmap=0;

while(<>)
{
	if(/^CHARMAP/) {
		$inmap=1;
	} elsif(/^END CHARMAP/) {
		$inmap=0;
	} elsif($inmap
	&& /^\s*\S+\s+\/x([0-9a-fA-F][0-9a-fA-F])\s+\<U([0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F])/) {
		$map[fromhex($1)]=fromhex($2);
	}
}
