#!/bin/sh
#
# Script to install a file (for portability reasons)
#
# (c) 2000 by The TTF2PT1 Project
# See COPYRIGHT for full license
#

[ $#  != 5 ] && {
	echo  "Use: $0 file-from file-to owner group mode" >&2
	exit 1
}

cp -f $1 $2 \
&& chown $3 $2 \
&& chgrp $4 $2 \
&& chmod 0$5 $2
