#!/usr/bin/perl
#
# Script to create a directory for installation
#
# (c) 2000 by The TTF2PT1 Project
# See COPYRIGHT for full license
#

if( $#ARGV!=0 && $#ARGV !=3) {
	die "Use: $0 dir-name [owner group mode]\n"
}

if( $#ARGV==3 ) {
	$owner = $ARGV[1];
	$group = $ARGV[2];
	eval "\$mode = 0$ARGV[3];";
} else {
	$owner = "root";
	$group = "bin";
	$mode = 0755;
}

@sl = split(/\//, $ARGV[0]);
$prefix = shift(@sl);
if($prefix eq "") {
	$prefix = "/" . shift(@sl);
}

while(1) {
	if( ! -d "$prefix" ) {
		die "Unable to create directory $prefix:\n$!\n"
			unless mkdir($prefix, $mode);
		die "Unable to change owner of $prefix to $owner\n"
			if system("chown $owner $prefix");
		die "Unable to change group of $prefix to $group\n"
			if system("chgrp $group $prefix");
	}
	if($#sl < 0) {
		last;
	}
	$prefix .= "/" . shift(@sl);
}
exit(0);
